import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Alert,AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{listCalendarBlocks}from'../data/calendarRepository';
import{CalendarBlock}from'../domain/types';
import{archiveMealSchedule,createMealSchedule,listMealSchedules,MealSchedule}from'../data/mealScheduleRepository';
import{confirmSleepSession,getSleepSchedule,getSleepSession,setSleepSchedule}from'../data/sleepScheduleRepository';
import{listScheduledRoutines}from'../data/scheduledRoutineRepository';
import{listTasks}from'../data/taskRepository';
import{syncDeviceCalendars}from'../integrations/deviceCalendar';

type Item={id:string;date:string;start:string;end?:string;title:string;kind:'event'|'routine'|'meal'|'sleep'|'task'|'deadline'};
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const clock=(d:Date)=>d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});
const monday=(d=new Date())=>{const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const dayBounds=(d:Date)=>({start:new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString(),end:new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).toISOString()});
const label=(d:Date)=>d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'});const previousDate=(d=new Date())=>dateKey(addDays(d,-1));

export function CalendarScreen(){
 const weekStart=useMemo(()=>monday(),[]),days=useMemo(()=>Array.from({length:14},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const[items,setItems]=useState<Item[]>([]),[syncing,setSyncing]=useState(false),[lastSync,setLastSync]=useState<Date|null>(null),[settings,setSettings]=useState(false),[mealDate,setMealDate]=useState(dateKey(new Date())),[mealTime,setMealTime]=useState('12:00'),[mealLabel,setMealLabel]=useState('Meal'),[meals,setMeals]=useState<MealSchedule[]>([]),[sleepTime,setSleepTime]=useState('23:30'),[actualSleep,setActualSleep]=useState('23:30'),[wakeTime,setWakeTime]=useState('07:30'),[sleepConfirmed,setSleepConfirmed]=useState(false);
 const load=useCallback(async()=>{
  const [routines,tasks]=await Promise.all([listScheduledRoutines(),listTasks()]);const out:Item[]=[];
  for(const d of days){const k=dateKey(d),b=dayBounds(d),events=await listCalendarBlocks(b.start,b.end);events.forEach((e:CalendarBlock)=>out.push({id:`e:${e.id}`,date:k,start:clock(new Date(e.startAt)),end:clock(new Date(e.endAt)),title:e.title,kind:e.kind==='meal'?'meal':e.kind==='sleep'?'sleep':e.kind==='task'?'task':'event'}));routines.forEach(r=>out.push({id:`r:${r.id}:${k}`,date:k,start:r.windowStart,end:r.windowEnd,title:r.name,kind:'routine'}))}
tasks.forEach(t=>{if(!t.deadlineAt)return;const d=new Date(t.deadlineAt),k=dateKey(d);if(days.some(x=>dateKey(x)===k))out.push({id:`t:${t.id}`,date:k,start:clock(d),title:`Deadline · ${t.name}`,kind:'deadline'})});out.sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start));setItems(out);
  const prev=previousDate(),[ms,sl,ss]=await Promise.all([listMealSchedules(mealDate),getSleepSchedule(),getSleepSession(prev)]);setMeals(ms);if(sl){setSleepTime(sl.startTime);if(!ss)setActualSleep(sl.startTime)}setSleepConfirmed(Boolean(ss));if(ss){setActualSleep(clock(new Date(ss.actualStartAt)));setWakeTime(clock(new Date(ss.actualEndAt)))}
 },[days,mealDate]);
 const sync=useCallback(async(silent=false)=>{if(syncing)return;setSyncing(true);try{await syncDeviceCalendars();setLastSync(new Date());await load()}catch(e){if(!silent)Alert.alert('Calendar sync failed',e instanceof Error?e.message:String(e));else await load()}finally{setSyncing(false)}},[load,syncing]);
 useEffect(()=>{sync(true)},[]);useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active')sync(true)});return()=>sub.remove()},[sync]);
 async function addMeal(){try{await createMealSchedule(mealLabel,mealTime,mealDate);await load()}catch(e){const m=e instanceof Error?e.message:String(e);Alert.alert('Cannot add meal',m.startsWith('TIME_CONFLICT:')?`This meal conflicts with ${m.slice(14)}.`:m)}}async function removeMeal(id:string){await archiveMealSchedule(id);await load()}async function saveSleep(){try{await setSleepSchedule(sleepTime);await load()}catch(e){Alert.alert('Cannot save sleep',e instanceof Error?e.message:String(e))}}async function confirmPreviousSleep(){try{const prev=previousDate(),start=new Date(`${prev}T${actualSleep}:00`);let end=new Date(`${dateKey(new Date())}T${wakeTime}:00`);if(end<=start)end=new Date(start.getTime()+480*60000);await confirmSleepSession(prev,start.toISOString(),end.toISOString());await load()}catch(e){Alert.alert('Cannot confirm sleep',e instanceof Error?e.message:String(e))}}
 return <ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><View style={s.header}><View><Text style={s.heading}>Calendar</Text><Text style={s.sub}>This week + next week</Text></View><View style={s.headActions}><Pressable onPress={()=>setSettings(v=>!v)} style={s.sync}><Text style={s.syncText}>⚙ Settings</Text></Pressable><Pressable onPress={()=>sync(false)} disabled={syncing} style={s.sync}><Text style={s.syncText}>{syncing?'Syncing…':lastSync?'↻ Synced':'↻ Sync'}</Text></Pressable></View></View>
 {settings?<View style={s.settings}><Text style={s.kicker}>APP-LOCAL CALENDAR SETTINGS</Text><Text style={s.note}>Outlook and Android Calendar are read-only. Edit external events in those calendar apps.</Text><Text style={s.settingTitle}>Meal blocks · 1h each · max 4/day</Text><View style={s.formRow}><TextInput value={mealDate} onChangeText={setMealDate} placeholder="YYYY-MM-DD" style={[s.input,s.dateInput]}/><TextInput value={mealTime} onChangeText={setMealTime} placeholder="HH:MM" style={[s.input,s.timeInput]}/><TextInput value={mealLabel} onChangeText={setMealLabel} placeholder="Meal" style={[s.input,s.flex]}/><Pressable onPress={addMeal} style={s.add}><Text style={s.addText}>Add</Text></Pressable></View>{meals.map(m=><View key={m.id} style={s.settingItem}><Text style={s.title}>{m.startTime} · {m.label}</Text><Pressable onPress={()=>removeMeal(m.id)}><Text style={s.remove}>Remove</Text></Pressable></View>)}<Text style={s.settingTitle}>Persistent sleep · planned 8h</Text><View style={s.formRow}><TextInput value={sleepTime} onChangeText={setSleepTime} placeholder="HH:MM" style={[s.input,s.flex]}/><Pressable onPress={saveSleep} style={s.add}><Text style={s.addText}>Save</Text></Pressable></View><Text style={s.settingTitle}>Previous night · {previousDate()}</Text><View style={s.formRow}><TextInput value={actualSleep} onChangeText={setActualSleep} placeholder="Sleep HH:MM" style={[s.input,s.flex]}/><TextInput value={wakeTime} onChangeText={setWakeTime} placeholder="Wake HH:MM" style={[s.input,s.flex]}/><Pressable onPress={confirmPreviousSleep} style={s.add}><Text style={s.addText}>{sleepConfirmed?'Update':'Confirm'}</Text></Pressable></View><Text style={s.note}>Planned sleep reserves 8h. Previous-night actual sleep and wake times replace that planned block after confirmation.</Text></View>:null}
 {days.map((d,i)=>{const k=dateKey(d),dayItems=items.filter(x=>x.date===k);return <View key={k} style={[s.day,i===7&&s.nextWeek]}><View style={s.dayHead}><Text style={s.dayTitle}>{label(d)}</Text>{k===dateKey(new Date())?<Text style={s.today}>TODAY</Text>:null}</View>{dayItems.length===0?<Text style={s.empty}>Free</Text>:dayItems.map(x=><View key={x.id} style={s.item}><View style={[s.dot,s[`dot_${x.kind}`]]}/><Text style={s.time}>{x.start}{x.end?`–${x.end}`:''}</Text><View style={{flex:1}}><Text style={s.title}>{x.title}</Text><Text style={s.kind}>{x.kind==='routine'?'default routine':x.kind}</Text></View></View>)}</View>})}<Text style={s.foot}>External events are read-only and sync automatically. Default routines, meals, sleep and scheduled tasks are app-local; task deadlines appear as markers.</Text></ScrollView>
}
const s=StyleSheet.create({container:{padding:18,paddingBottom:90,gap:10},header:{gap:10,marginBottom:3},headActions:{flexDirection:'row',gap:7},heading:{fontSize:30,fontWeight:'900'},sub:{opacity:.5,marginTop:2},sync:{paddingHorizontal:12,paddingVertical:9,borderRadius:12,backgroundColor:'#EEF1F6'},syncText:{fontWeight:'900',fontSize:12},settings:{backgroundColor:'white',borderRadius:18,padding:14,gap:9,elevation:1},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1,opacity:.5},note:{fontSize:11,opacity:.5,lineHeight:16},settingTitle:{fontSize:13,fontWeight:'900',marginTop:3},formRow:{flexDirection:'row',gap:6,alignItems:'center'},input:{minHeight:40,borderWidth:1,borderColor:'#E1E5EC',borderRadius:10,paddingHorizontal:9,backgroundColor:'#FAFBFC',fontSize:12},dateInput:{width:104},timeInput:{width:64},flex:{flex:1},add:{paddingHorizontal:11,minHeight:40,borderRadius:10,backgroundColor:'#246BFD',alignItems:'center',justifyContent:'center'},addText:{color:'white',fontWeight:'900',fontSize:12},settingItem:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:5},remove:{fontSize:11,fontWeight:'800',color:'#B83B3B'},day:{backgroundColor:'white',borderRadius:18,padding:14,gap:7,elevation:1},nextWeek:{marginTop:8,borderTopWidth:3,borderTopColor:'#E4E8F0'},dayHead:{flexDirection:'row',alignItems:'center',gap:8},dayTitle:{fontSize:16,fontWeight:'900'},today:{fontSize:9,fontWeight:'900',paddingHorizontal:7,paddingVertical:3,borderRadius:999,backgroundColor:'#172033',color:'white'},empty:{fontSize:12,opacity:.35,paddingVertical:5},item:{flexDirection:'row',alignItems:'flex-start',gap:8,paddingVertical:5,borderTopWidth:1,borderTopColor:'#F2F3F6'},dot:{width:7,height:7,borderRadius:99,marginTop:6,backgroundColor:'#697386'},dot_event:{backgroundColor:'#246BFD'},dot_routine:{backgroundColor:'#7A55C7'},dot_meal:{backgroundColor:'#D08A28'},dot_sleep:{backgroundColor:'#44546A'},dot_task:{backgroundColor:'#15803D'},dot_deadline:{backgroundColor:'#B83B3B'},time:{width:92,fontSize:11,fontWeight:'800',opacity:.65},title:{fontSize:13,fontWeight:'800'},kind:{fontSize:10,opacity:.4,marginTop:1},foot:{fontSize:11,opacity:.4,lineHeight:16,textAlign:'center',paddingHorizontal:8,paddingTop:5}});
