import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { listTasks } from '../data/taskRepository';
import { applyReward, Wallet } from '../data/economyRepository';
import { finishSession, startSession } from '../data/sessionRepository';
import { isHoliday } from '../data/holidayRepository';
import { grantAnnualLeaveMinutes, recordHolidayWork } from '../data/leaveRepository';
import { addDrawProgress } from '../data/drawBankRepository';
import { completeAcceptedInvitation } from '../data/taskInvitationRepository';
import { chooseRestWithCoin, scheduleNextDrawAfter, startRandomRest, RestState } from '../data/restRepository';
import { GAME_CONFIG } from '../config/gameConfig';
import { eligibleTasks, difficultyTasks } from '../engine/eligibility';
import { commitmentMinutes, weightedTaskDraw } from '../engine/random';
import { calculateSessionReward } from '../engine/rewards';
import { taskCompletionReward } from '../engine/rewardPools';
import { drawInvitationBonus, InvitationBonus } from '../engine/invitationBonus';
import { DrawMode, SessionPool, Task } from '../domain/types';
import { markTaskCompleted } from '../services/taskService';
type Phase='draw'|'timer'|'settlement'|'reward';type SelectionMode='random_task'|'fixed_task'|'fixed_time';type RewardResult={coin:number;xp:number;multiplier:number;overtimeMinutes:number;multiTask:number;compLeaveDays?:number;drawProgress?:number;taskCoinBonus?:number;invitationBonus?:InvitationBonus;wallet?:Wallet;rest?:RestState|null};
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
export function FocusFlow({pool=30,freeMinutes=30,initialTaskId,onClose}:{pool?:SessionPool;freeMinutes?:number;initialTaskId?:string;onClose:()=>void}){
 const[phase,setPhase]=useState<Phase>('draw'),[selectionMode,setSelectionMode]=useState<SelectionMode>('random_task'),[mode,setMode]=useState<DrawMode>('normal');const[task,setTask]=useState<Task|null>(null),[fixedCandidates,setFixedCandidates]=useState<Task[]>([]),[targetSeconds,setTargetSeconds]=useState(0),[chosenMinutes,setChosenMinutes]=useState<number>(pool),[elapsedSeconds,setElapsedSeconds]=useState(0);const[completed,setCompleted]=useState(false),[additionalTasks,setAdditionalTasks]=useState<Task[]>([]),[completionCandidates,setCompletionCandidates]=useState<Task[]>([]),[sessionId,setSessionId]=useState<string|null>(null),[reward,setReward]=useState<RewardResult|null>(null);
 useEffect(()=>{if(phase!=='timer')return;const id=setInterval(()=>setElapsedSeconds(v=>v+1),1000);return()=>clearInterval(id)},[phase]);useEffect(()=>{if(phase==='draw'&&selectionMode==='fixed_task')listTasks().then(t=>setFixedCandidates(eligibleTasks(t))).catch(e=>Alert.alert('Could not load tasks',String(e)))},[phase,selectionMode]);useEffect(()=>{if(!initialTaskId||phase!=='draw')return;listTasks().then(tasks=>{const s=tasks.find(t=>t.id===initialTaskId&&t.status==='active');if(s){setSelectionMode('fixed_task');setFixedCandidates(eligibleTasks(tasks));randomizeTime(s)}})},[initialTaskId]);
 const remaining=targetSeconds-elapsedSeconds,overtime=Math.max(0,-remaining),displaySeconds=Math.abs(remaining),clock=useMemo(()=>`${String(Math.floor(displaySeconds/60)).padStart(2,'0')}:${String(displaySeconds%60).padStart(2,'0')}`,[displaySeconds]);function randomizeTime(s:Task){setTask(s);setTargetSeconds(commitmentMinutes(s,pool,freeMinutes)*60)}async function draw(){const ts=await listTasks(),cs=mode==='normal'?eligibleTasks(ts):difficultyTasks(ts),s=weightedTaskDraw(cs);if(!s){Alert.alert('No eligible tasks');return}setTask(s);setTargetSeconds(selectionMode==='fixed_time'?chosenMinutes*60:commitmentMinutes(s,pool,freeMinutes)*60)}async function start(){if(!task)return;setSessionId(await startSession({taskId:task.id,pool,drawMode:mode,commitmentMinutes:Math.round(targetSeconds/60)}));setElapsedSeconds(0);setPhase('timer')}async function finish(){const ts=await listTasks();setCompletionCandidates(eligibleTasks(ts).filter(c=>c.id!==task?.id));setPhase('settlement')}function toggleAdditional(c:Task){setAdditionalTasks(x=>x.some(i=>i.id===c.id)?x.filter(i=>i.id!==c.id):x.length>=2?x:[...x,c])}
 async function settle(){if(!task||!sessionId)return;const workedMinutes=Math.max(1,Math.ceil(elapsedSeconds/60));await finishSession(sessionId,workedMinutes);if(completed)await markTaskCompleted(task.id);for(const x of additionalTasks)await markTaskCompleted(x.id);const done=[...(completed?[task]:[]),...additionalTasks],count=done.length,calc=calculateSessionReward({actualMinutes:workedMinutes,commitmentMinutes:Math.round(targetSeconds/60),difficulty:task.difficulty,drawMode:mode,completedTaskCount:count});let drawProgress=0,taskCoinBonus=0;if(count){const per=Math.max(5,workedMinutes/count);for(const t of done){const r=taskCompletionReward(t.difficulty,per);drawProgress+=r.drawProgress;taskCoinBonus+=r.coin}drawProgress=Number(drawProgress.toFixed(2));await addDrawProgress(drawProgress,`session:${sessionId}:tasks`)}let invitationBonus:InvitationBonus|undefined,invitationCoin=0;if(initialTaskId&&completed&&task.id===initialTaskId&&await completeAcceptedInvitation(task.id)){invitationBonus=drawInvitationBonus();if(invitationBonus.type==='coin')invitationCoin=invitationBonus.amount;else if(invitationBonus.type==='annual_leave_minutes')await grantAnnualLeaveMinutes(invitationBonus.minutes);else await addDrawProgress(invitationBonus.amount,`session:${sessionId}:invitation`)}const wallet=await applyReward({sessionId,source:invitationBonus?'invited_task':'focus_session',coin:calc.coin+taskCoinBonus+invitationCoin,xp:calc.xp,multiplier:calc.multiplier}),today=localDateKey(),compLeaveDays=await isHoliday(today)?await recordHolidayWork(workedMinutes,today,sessionId):0,rest=count?await startRandomRest(Math.random,new Date(),sessionId):null;setReward({...calc,coin:calc.coin+taskCoinBonus+invitationCoin,wallet,compLeaveDays,drawProgress,taskCoinBonus,invitationBonus,rest});setPhase('reward')}
 if(phase==='draw')return <ScrollView contentContainerStyle={styles.settlement}><Text style={styles.kicker}>{initialTaskId?'RANDOM INVITATION':`${pool} MIN POOL`}</Text><Text style={styles.title}>{initialTaskId?'Invitation accepted':'Choose how to start'}</Text>{initialTaskId&&task?<View style={styles.card}><Text style={styles.task}>{task.name}</Text><Text style={styles.meta}>Random commitment · {Math.round(targetSeconds/60)} min</Text><Text style={styles.inviteHint}>Complete the invited task to reveal a one-time mystery bonus.</Text><Pressable onPress={start} style={styles.primary}><Text style={styles.primaryText}>Start</Text></Pressable></View>:<><View style={styles.modeRow}><Pressable onPress={()=>{setSelectionMode('random_task');setTask(null)}} style={[styles.chip,selectionMode==='random_task'&&styles.selected]}><Text style={selectionMode==='random_task'?styles.selectedText:styles.chipText}>Random task + time</Text></Pressable><Pressable onPress={()=>{setSelectionMode('fixed_task');setTask(null)}} style={[styles.chip,selectionMode==='fixed_task'&&styles.selected]}><Text style={selectionMode==='fixed_task'?styles.selectedText:styles.chipText}>Choose task + random time</Text></Pressable><Pressable onPress={()=>{setSelectionMode('fixed_time');setTask(null);setTargetSeconds(chosenMinutes*60)}} style={[styles.chip,selectionMode==='fixed_time'&&styles.selected]}><Text style={selectionMode==='fixed_time'?styles.selectedText:styles.chipText}>Choose time + random task</Text></Pressable></View>{selectionMode==='fixed_task'?<>{fixedCandidates.map(c=><Pressable key={c.id} onPress={()=>randomizeTime(c)} style={styles.option}><Text style={styles.optionTitle}>{c.name}</Text></Pressable>)}{task?<TaskResult task={task} minutes={Math.round(targetSeconds/60)} onStart={start} onReroll={()=>randomizeTime(task)}/>:null}</>:selectionMode==='fixed_time'?<><Text style={styles.section}>Choose focus time</Text><View style={styles.modeRow}>{([15,30,45,60,90] as const).map(m=><Pressable key={m} onPress={()=>{setChosenMinutes(m);setTask(null);setTargetSeconds(m*60)}} style={[styles.chip,chosenMinutes===m&&styles.selected]}><Text style={chosenMinutes===m?styles.selectedText:styles.chipText}>{m} min</Text></Pressable>)}</View>{task?<TaskResult task={task} minutes={chosenMinutes} onStart={start} onReroll={draw}/>:<Pressable onPress={draw} style={styles.primary}><Text style={styles.primaryText}>DRAW TASK</Text></Pressable>}</>:task?<TaskResult task={task} minutes={Math.round(targetSeconds/60)} onStart={start} onReroll={draw}/>:<Pressable onPress={draw} style={styles.primary}><Text style={styles.primaryText}>DRAW</Text></Pressable>}</>}<Pressable onPress={onClose}><Text style={styles.close}>Cancel</Text></Pressable></ScrollView>;
 if(phase==='timer')return <View style={styles.page}><Text style={styles.kicker}>{overtime?'OVERTIME':initialTaskId?'INVITED FOCUS':'FOCUS'}</Text><Text style={styles.task}>{task?.name}</Text><Text style={styles.timer}>{overtime?'+':''}{clock}</Text><Pressable onPress={finish} style={styles.primary}><Text style={styles.primaryText}>{remaining>0?'End Early':'Finish'}</Text></Pressable></View>;
 if(phase==='settlement')return <ScrollView contentContainerStyle={styles.settlement}><Text style={styles.kicker}>SETTLEMENT</Text><Text style={styles.title}>{Math.ceil(elapsedSeconds/60)} min worked</Text><Pressable onPress={()=>setCompleted(false)} style={[styles.option,!completed&&styles.optionSelected]}><Text>Session only</Text></Pressable><Pressable onPress={()=>setCompleted(true)} style={[styles.option,completed&&styles.optionSelected]}><Text>Primary task completed ✓</Text></Pressable><Text style={styles.section}>Also completed</Text>{completionCandidates.map(c=><Pressable key={c.id} onPress={()=>toggleAdditional(c)} style={styles.option}><Text>{additionalTasks.some(i=>i.id===c.id)?'✓ ':''}{c.name}</Text></Pressable>)}<Pressable onPress={settle} style={styles.primary}><Text style={styles.primaryText}>Confirm</Text></Pressable></ScrollView>;
 async function chooseRest(m:number){try{const rest=await chooseRestWithCoin(m);setReward(r=>r?{...r,rest,wallet:r.wallet?{...r.wallet,coin:r.wallet.coin-GAME_CONFIG.mandatoryRest.chooseCoinCost}:r.wallet}:r)}catch(e){Alert.alert('Cannot choose rest',String(e))}}async function setNextDrawDelay(m:number){try{const rest=await scheduleNextDrawAfter(m);setReward(r=>r?{...r,rest}:r)}catch(e){Alert.alert('Cannot schedule',String(e))}}
 return <ScrollView contentContainerStyle={styles.settlement}><Text style={styles.kicker}>COMPLETE ✓</Text><Text style={styles.reward}>+ {reward?.coin??0} Coin</Text><Text style={styles.reward}>+ {reward?.xp??0} XP</Text>{reward?.drawProgress?<Text style={styles.comp}>+ {reward.drawProgress.toFixed(2)} Draw Credit</Text>:null}{reward?.invitationBonus?<View style={styles.inviteBonus}><Text style={styles.kicker}>INVITATION MYSTERY BONUS</Text><Text style={styles.comp}>{reward.invitationBonus.label}</Text></View>:null}{reward?.compLeaveDays?<Text style={styles.comp}>+ {reward.compLeaveDays.toFixed(2)} day Comp Leave</Text>:null}<View style={styles.card}><Text style={styles.wallet}>🪙 {reward?.wallet?.coin??0} · XP {reward?.wallet?.xp??0} · Lv. {reward?.wallet?.level??1}</Text></View>{reward?.rest?<View style={styles.card}><Text style={styles.section}>Mandatory Rest</Text><Text style={styles.reward}>{reward.rest.restMinutes} min</Text><View style={styles.modeRow}>{GAME_CONFIG.mandatoryRest.optionsMinutes.map(m=><Pressable key={m} onPress={()=>chooseRest(m)} style={styles.chip}><Text>{m}m</Text></Pressable>)}</View><Text style={styles.meta}>Next task draw:</Text><View style={styles.modeRow}>{GAME_CONFIG.mandatoryRest.nextDrawDelayOptionsMinutes.map(m=><Pressable key={m} onPress={()=>setNextDrawDelay(m)} style={styles.chip}><Text>{m===0?'After rest':`+${m}m`}</Text></Pressable>)}</View></View>:null}<Pressable onPress={onClose} style={styles.primary}><Text style={styles.primaryText}>Back to Today</Text></Pressable></ScrollView>;
}
function TaskResult({task,minutes,onStart,onReroll}:{task:Task;minutes:number;onStart:()=>void;onReroll:()=>void}){return <View style={styles.card}><Text style={styles.task}>{task.name}</Text><Text style={styles.meta}>{task.difficulty.replace('_',' ')} · {minutes} min</Text><Pressable onPress={onStart} style={styles.primary}><Text style={styles.primaryText}>Start</Text></Pressable><Pressable onPress={onReroll} style={styles.secondary}><Text>↻ Reroll</Text></Pressable></View>}
const styles=StyleSheet.create({page:{flex:1,padding:24,justifyContent:'center',gap:18,backgroundColor:'#F7F8FA'},settlement:{padding:24,paddingBottom:70,gap:14,backgroundColor:'#F7F8FA'},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.5,opacity:.5},title:{fontSize:30,fontWeight:'800'},section:{fontSize:17,fontWeight:'800'},modeRow:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:10,borderRadius:999,backgroundColor:'#E9EDF4'},selected:{backgroundColor:'#246BFD'},selectedText:{color:'white',fontWeight:'800'},chipText:{fontWeight:'700'},card:{padding:20,borderRadius:24,backgroundColor:'white',gap:14},task:{fontSize:24,fontWeight:'800'},meta:{opacity:.55},timer:{fontSize:64,fontWeight:'800'},primary:{minHeight:54,borderRadius:17,backgroundColor:'#246BFD',alignItems:'center',justifyContent:'center'},primaryText:{color:'white',fontWeight:'900'},secondary:{minHeight:46,alignItems:'center',justifyContent:'center'},close:{textAlign:'center',opacity:.5},option:{padding:16,borderRadius:16,backgroundColor:'white'},optionSelected:{borderWidth:2,borderColor:'#246BFD'},optionTitle:{fontWeight:'800'},reward:{fontSize:28,fontWeight:'900'},comp:{fontSize:20,fontWeight:'900'},wallet:{fontSize:18,fontWeight:'800'},inviteHint:{fontSize:13,fontWeight:'800',color:'#6B4EFF'},inviteBonus:{padding:16,borderRadius:18,backgroundColor:'#F1EEFF',gap:6}});