import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getWallet, Wallet } from '../data/economyRepository';
import { listUpcomingHolidays, scheduleHoliday, HolidayDay } from '../data/holidayRepository';
import { getLeaveBalance, LeaveBalance, syncLevelAnnualLeaveBonus, useAnnualLeaveMinutes, useCompLeave } from '../data/leaveRepository';
import { getCurrentWeeklyPass, extendCurrentWeeklyPass, consumeWeeklyPass, WeeklyHolidayPass } from '../data/weeklyHolidayPassRepository';
import { getDrawBank } from '../data/drawBankRepository';
import { RewardPool, TenDrawChoice } from '../engine/rewardPools';
import { settlePrizeDraw, getTenDrawChoices, claimTenDrawChoice } from '../services/prizeService';
const MINUTE_OPTIONS=[30,60,90,120,240,480] as const;
function localDateKey(date=new Date()){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
type DrawBank={balance:number;availableDraws:number;tenDrawReady:boolean;spentDraws:number;spentByPool:Record<RewardPool,number>};
export function RewardsScreen(){
 const[wallet,setWallet]=useState<Wallet>({coin:0,xp:0,level:1});const[date,setDate]=useState(localDateKey());const[startTime,setStartTime]=useState('09:00');const[holidays,setHolidays]=useState<HolidayDay[]>([]);const[leave,setLeave]=useState<LeaveBalance|null>(null);const[minutes,setMinutes]=useState<number>(60);const[weeklyPass,setWeeklyPass]=useState<WeeklyHolidayPass|null>(null);const[bank,setBank]=useState<DrawBank|null>(null);const[tenPool,setTenPool]=useState<RewardPool|null>(null);
 async function reload(){const today=localDateKey();const w=await getWallet();await syncLevelAnnualLeaveBonus(w.level);const[h,l,p,b]=await Promise.all([listUpcomingHolidays(today),getLeaveBalance(),getCurrentWeeklyPass(),getDrawBank()]);setWallet(w);setHolidays(h);setLeave(l);setWeeklyPass(p);setBank(b);}
 useEffect(()=>{reload().catch(console.error)},[]);
 async function act(fn:()=>Promise<unknown>,title:string){try{await fn();await reload();}catch(e){Alert.alert(title,e instanceof Error?e.message:String(e));}}
 async function singleDraw(pool:RewardPool){await act(async()=>{const result=await settlePrizeDraw(pool);Alert.alert(pool==='time'?'Time Pool':'Function Pool',result.reward.label);},'Cannot draw');}
 async function tenChoice(choice:TenDrawChoice){await act(async()=>{await claimTenDrawChoice(choice.pool,choice);setTenPool(null);Alert.alert('10-Draw Limited Reward',choice.label);},'Cannot claim');}
 const days=minutes/480;const tenChoices=tenPool?getTenDrawChoices(tenPool):[];
 return <ScrollView contentContainerStyle={styles.container}><Text style={styles.heading}>Rewards</Text><Text style={styles.subheading}>Bank rewards now. Choose the pool when you draw.</Text>
 <View style={styles.card}><Text style={styles.kicker}>DRAW BANK</Text><Text style={styles.drawBalance}>{bank?.balance.toFixed(2)??'0.00'}</Text><Text style={styles.meta}>{bank?.availableDraws??0} full draws available · fractional progress carries forward.</Text><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${Math.min(100,((bank?.balance??0)%10)/10*100)}%`}]} /></View><Text style={styles.meta}>{bank?.tenDrawReady?'10-Draw Limited Reward ready — choose a pool.':`${(10-(bank?.balance??0)%10).toFixed(2)} Draw Credit to next 10-draw unlock.`}</Text><View style={styles.poolGrid}><PoolCard title="TIME POOL" subtitle="Annual Leave & protected time" onDraw={()=>singleDraw('time')} onTen={()=>setTenPool('time')} draws={bank?.availableDraws??0} tenReady={bank?.tenDrawReady??false}/><PoolCard title="FUNCTION POOL" subtitle="Freedom, coupons & utility" onDraw={()=>singleDraw('function')} onTen={()=>setTenPool('function')} draws={bank?.availableDraws??0} tenReady={bank?.tenDrawReady??false}/></View></View>
 {tenPool?<View style={styles.card}><Text style={styles.kicker}>{tenPool.toUpperCase()} · 10-DRAW LIMITED</Text><Text style={styles.big}>Choose 1 of 3</Text><Text style={styles.meta}>Consumes 10 banked Draw Credits. The limited reward replaces ten individual draws.</Text>{tenChoices.map(choice=><Pressable key={choice.label} onPress={()=>tenChoice(choice)} style={styles.choice}><Text style={styles.choiceTitle}>{choice.label}</Text><Text style={styles.meta}>Guaranteed limited reward</Text></Pressable>)}<Pressable onPress={()=>setTenPool(null)} style={styles.secondary}><Text style={styles.secondaryText}>Cancel</Text></Pressable></View>:null}
 <View style={styles.card}><Text style={styles.kicker}>TIME OFF BALANCE</Text><View style={styles.balanceRow}><Balance label="Weekly Pass" value={weeklyPass?.active?'1':'0'}/><Balance label="Annual Leave" value={`${leave?.annualAvailableDays.toFixed(3)??'20.000'}d`}/><Balance label="Comp Leave" value={`${leave?.compDays.toFixed(3)??'0.000'}d`}/></View><Text style={styles.meta}>1 day = 480 min. Annual Leave is permanent; the Weekly Holiday Pass expires.</Text></View>
 <View style={styles.card}><Text style={styles.kicker}>WEEKLY HOLIDAY PASS</Text><Text style={styles.big}>{weeklyPass?.active?'Available':'Unavailable'}</Text>{weeklyPass?<Text style={styles.meta}>Expires {new Date(weeklyPass.expiresAt).toLocaleString()} {weeklyPass.extended?'· extended':''}</Text>:null}<Pressable disabled={!weeklyPass?.active||weeklyPass?.extended} onPress={()=>act(()=>extendCurrentWeeklyPass(),'Cannot extend')} style={[styles.primary,(!weeklyPass?.active||weeklyPass?.extended)&&styles.disabled]}><Text style={styles.primaryText}>Extend 7 days · 60 Coin</Text></Pressable><Text style={styles.wallet}>Wallet · 🪙 {wallet.coin}</Text></View>
 <View style={styles.card}><Text style={styles.kicker}>PLAN TIME OFF</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={styles.input}/><View style={styles.quickRow}><Pressable onPress={()=>setDate(localDateKey())} style={styles.quick}><Text>Today</Text></Pressable><Pressable onPress={()=>{const d=new Date();d.setDate(d.getDate()+1);setDate(localDateKey(d))}} style={styles.quick}><Text>Tomorrow</Text></Pressable></View><Text style={styles.meta}>Protected time</Text><View style={styles.quickRow}>{MINUTE_OPTIONS.map(v=><Pressable key={v} onPress={()=>setMinutes(v)} style={[styles.quick,minutes===v&&styles.quickSelected]}><Text style={minutes===v&&styles.quickSelectedText}>{v===480?'1 day':`${v}m`}</Text></Pressable>)}</View><Text style={styles.meta}>{minutes} min = {days.toFixed(3)}d Annual Leave</Text>{minutes<480?<><Text style={styles.meta}>Start time</Text><TextInput value={startTime} onChangeText={setStartTime} placeholder="09:00" style={styles.input}/></>:null}<Pressable disabled={minutes!==480||!weeklyPass?.active} onPress={()=>act(()=>consumeWeeklyPass(date),'Cannot use weekly pass')} style={[styles.primary,(minutes!==480||!weeklyPass?.active)&&styles.disabled]}><Text style={styles.primaryText}>Use Weekly Holiday Pass · full day</Text></Pressable><Pressable onPress={()=>act(()=>useAnnualLeaveMinutes(date,startTime,minutes),'Cannot use annual leave')} style={styles.secondary}><Text style={styles.secondaryText}>Use {days.toFixed(3)}d Annual Leave</Text></Pressable><Pressable onPress={()=>act(()=>useCompLeave(date,days,startTime),'Cannot use comp leave')} style={styles.secondary}><Text style={styles.secondaryText}>Use {days.toFixed(3)}d Comp Leave</Text></Pressable></View>
 <View style={styles.card}><Text style={styles.kicker}>UPCOMING HOLIDAYS</Text>{holidays.length===0?<Text style={styles.meta}>No planned holidays yet.</Text>:holidays.map(h=><View key={h.localDate} style={styles.holidayRow}><View><Text style={styles.holidayDate}>{h.localDate}</Text>{h.name?<Text style={styles.meta}>{h.name}</Text>:null}</View><Text style={styles.meta}>{h.source==='fixed'?'HK holiday':h.source.replace('_',' ')}</Text></View>)}</View></ScrollView>;
}
function PoolCard({title,subtitle,onDraw,onTen,draws,tenReady}:{title:string;subtitle:string;onDraw:()=>void;onTen:()=>void;draws:number;tenReady:boolean}){return <View style={styles.poolCard}><Text style={styles.poolTitle}>{title}</Text><Text style={styles.meta}>{subtitle}</Text><Pressable disabled={draws<1} onPress={onDraw} style={[styles.primary,draws<1&&styles.disabled]}><Text style={styles.primaryText}>Draw ×1</Text></Pressable><Pressable disabled={!tenReady} onPress={onTen} style={[styles.tenButton,!tenReady&&styles.disabled]}><Text style={styles.tenText}>10-Draw · Pick 1 of 3</Text></Pressable></View>}
function Balance({label,value}:{label:string;value:string}){return <View style={styles.balance}><Text style={styles.balanceValue}>{value}</Text><Text style={styles.balanceLabel}>{label}</Text></View>}
const styles=StyleSheet.create({container:{padding:20,paddingBottom:90,gap:16},heading:{fontSize:30,fontWeight:'800'},subheading:{opacity:.58,marginTop:-8},card:{backgroundColor:'white',borderRadius:22,padding:18,gap:12,elevation:1},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.3,opacity:.5},big:{fontSize:25,fontWeight:'900'},drawBalance:{fontSize:44,fontWeight:'900'},meta:{fontSize:13,opacity:.58,lineHeight:19},wallet:{fontWeight:'800'},balanceRow:{flexDirection:'row',gap:8},balance:{flex:1,padding:12,borderRadius:14,backgroundColor:'#F4F6F9'},balanceValue:{fontSize:20,fontWeight:'900'},balanceLabel:{fontSize:11,opacity:.55,marginTop:4},progressTrack:{height:10,borderRadius:999,backgroundColor:'#E6EAF1',overflow:'hidden'},progressFill:{height:'100%',borderRadius:999,backgroundColor:'#246BFD'},poolGrid:{gap:10},poolCard:{padding:14,borderRadius:18,backgroundColor:'#F4F6F9',gap:9},poolTitle:{fontWeight:'900',fontSize:16},primary:{minHeight:50,borderRadius:16,backgroundColor:'#246BFD',alignItems:'center',justifyContent:'center',paddingHorizontal:16},primaryText:{color:'white',fontWeight:'900'},tenButton:{minHeight:48,borderRadius:16,backgroundColor:'#171B24',alignItems:'center',justifyContent:'center'},tenText:{color:'white',fontWeight:'900'},disabled:{opacity:.35},choice:{padding:16,borderRadius:16,backgroundColor:'#F4F6F9',gap:4},choiceTitle:{fontSize:16,fontWeight:'900'},secondary:{minHeight:50,borderRadius:16,backgroundColor:'#EEF1F6',alignItems:'center',justifyContent:'center'},secondaryText:{fontWeight:'800'},input:{minHeight:48,borderWidth:1,borderColor:'#E1E5EC',borderRadius:14,paddingHorizontal:14},quickRow:{flexDirection:'row',flexWrap:'wrap',gap:8},quick:{paddingHorizontal:14,paddingVertical:9,borderRadius:12,backgroundColor:'#EEF1F6'},quickSelected:{backgroundColor:'#246BFD'},quickSelectedText:{color:'white',fontWeight:'800'},holidayRow:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5},holidayDate:{fontWeight:'800'}});
