import React,{useEffect,useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import DateTimePicker from'@react-native-community/datetimepicker';
import{listUpcomingHolidays,HolidayDay}from'../data/holidayRepository';
import{cancelPlannedTimeOff,getLeaveBalance,LeaveBalance,syncLevelAnnualLeaveBonus,useAnnualLeaveMinutes,useCompLeave,listPlannedTimeOff,PlannedTimeOff}from'../data/leaveRepository';
import{getCurrentWeeklyPass,consumeWeeklyPass,WeeklyHolidayPass}from'../data/weeklyHolidayPassRepository';
import{getWallet}from'../data/economyRepository';
const OPTIONS=[30,60,90,120,240,480]as const;
const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const timeKey=(d:Date)=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
const dt=(date:string,time='12:00')=>new Date(`${date}T${time}:00`);
const pretty=(iso:string|null)=>iso?new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';
export function TimeOffScreen(){const[date,setDate]=useState(localDateKey()),[time,setTime]=useState('09:00'),[minutes,setMinutes]=useState<number>(60),[showDate,setShowDate]=useState(false),[showTime,setShowTime]=useState(false),[leave,setLeave]=useState<LeaveBalance|null>(null),[pass,setPass]=useState<WeeklyHolidayPass|null>(null),[planned,setPlanned]=useState<PlannedTimeOff[]>([]),[holidays,setHolidays]=useState<HolidayDay[]>([]),[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false);
async function reload(){const w=await getWallet();await syncLevelAnnualLeaveBonus(w.level);const[l,p,pto,h]=await Promise.all([getLeaveBalance(),getCurrentWeeklyPass(),listPlannedTimeOff(localDateKey()),listUpcomingHolidays(localDateKey())]);setLeave(l);setPass(p);setPlanned(pto);setHolidays(h)}useEffect(()=>{reload().catch(console.error)},[]);
function flash(x:string){setNotice(x);setTimeout(()=>setNotice(null),4500)}async function act<T>(fn:()=>Promise<T>,ok:(x:T)=>string){if(busy)return;setBusy(true);try{const x=await fn();await reload();flash(`✓ ${ok(x)}`)}catch(e){Alert.alert('Could not update time off',e instanceof Error?e.message:String(e))}finally{setBusy(false)}}function confirm(title:string,msg:string,fn:()=>void){Alert.alert(title,msg,[{text:'Cancel',style:'cancel'},{text:'Confirm',onPress:fn}])}
const days=minutes/480,end=new Date(dt(date,time).getTime()+minutes*60000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),label=minutes===480?`${date} · Full day`:`${date} · ${time}-${end}`;
function useAnnual(){confirm('Confirm Annual Leave',`${label}\nCost ${days.toFixed(3)}d`,()=>act(()=>useAnnualLeaveMinutes(date,time,minutes),()=>`Annual Leave scheduled · ${label}`))}function useComp(){confirm('Confirm Comp Leave',`${label}\nCost ${days.toFixed(3)}d`,()=>act(()=>useCompLeave(date,days,time),()=>`Comp Leave scheduled · ${label}`))}function undo(p:PlannedTimeOff){confirm('Undo planned leave','Used leave is not refunded. 75% of unused time is returned.',()=>act(()=>cancelPlannedTimeOff(p),r=>`${r.refundedMinutes.toFixed(0)} min refunded · ${r.forfeitedMinutes.toFixed(0)} min cancellation cost`))}
return <ScrollView contentContainerStyle={s.container}>{notice?<View style={s.notice}><Text style={s.noticeText}>{notice}</Text></View>:null}<Text style={s.heading}>Time Off</Text><Text style={s.sub}>Plan leave without crowding the Rewards screen.</Text><View style={s.card}><Text style={s.kicker}>BALANCE</Text><View style={s.row}><Balance label="Weekly Pass" value={pass?.active?'1':'0'}/><Balance label="Annual" value={`${leave?.annualAvailableDays.toFixed(3)??'0'}d`}/><Balance label="Comp" value={`${leave?.compDays.toFixed(3)??'0'}d`}/></View></View><View style={s.card}><Text style={s.kicker}>PLAN TIME OFF</Text><Pressable onPress={()=>setShowDate(true)} style={s.picker}><Text style={s.strong}>{date}</Text><Text style={s.action}>Choose date</Text></Pressable>{showDate?<DateTimePicker value={dt(date)} mode="date" minimumDate={new Date()} onChange={(e,v)=>{setShowDate(false);if(e.type==='set'&&v)setDate(localDateKey(v))}}/>:null}<View style={s.wrap}>{OPTIONS.map(v=><Pressable key={v} onPress={()=>setMinutes(v)} style={[s.chip,minutes===v&&s.selected]}><Text style={minutes===v&&s.white}>{v===480?'1 day':`${v}m`}</Text></Pressable>)}</View>{minutes<480?<><Pressable onPress={()=>setShowTime(true)} style={s.picker}><Text style={s.strong}>{time}</Text><Text style={s.action}>Choose time</Text></Pressable>{showTime?<DateTimePicker value={dt(date,time)} mode="time" is24Hour onChange={(e,v)=>{setShowTime(false);if(e.type==='set'&&v)setTime(timeKey(v))}}/>:null}</>:null}<Text style={s.strong}>Protected · {label}</Text><Pressable disabled={busy||minutes!==480||!pass?.active} onPress={()=>confirm('Use Weekly Pass',label,()=>act(()=>consumeWeeklyPass(date),()=>`Weekly Pass used · ${date}`))} style={[s.primary,(minutes!==480||!pass?.active)&&s.disabled]}><Text style={s.primaryText}>Use Weekly Pass</Text></Pressable><Pressable disabled={busy} onPress={useAnnual} style={s.secondary}><Text style={s.strong}>Use {days.toFixed(3)}d Annual Leave</Text></Pressable><Pressable disabled={busy} onPress={useComp} style={s.secondary}><Text style={s.strong}>Use {days.toFixed(3)}d Comp Leave</Text></Pressable></View><View style={s.card}><Text style={s.kicker}>PLANNED</Text>{planned.length===0?<Text style={s.meta}>No upcoming leave.</Text>:planned.slice(0,8).map(p=><View key={p.id} style={s.item}><View style={{flex:1}}><Text style={s.strong}>{p.localDate}</Text><Text style={s.meta}>{p.type==='annual_leave'?'Annual':'Comp'} · {p.fullDay?'Full day':`${pretty(p.startAt)}-${pretty(p.endAt)}`}</Text></View><Pressable onPress={()=>undo(p)} style={s.undo}><Text style={s.undoText}>Undo</Text></Pressable></View>)}</View><View style={s.card}><Text style={s.kicker}>UPCOMING HOLIDAYS</Text>{holidays.slice(0,3).map(h=><View key={`${h.localDate}:${h.source}`} style={s.item}><Text style={s.strong}>{h.localDate}</Text><Text style={s.meta}>{h.name??h.source.replaceAll('_',' ')}</Text></View>)}</View></ScrollView>}
function Balance({label,value}:{label:string;value:string}){return <View style={s.balance}><Text style={s.balanceValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({container:{padding:20,paddingBottom:90,gap:14},heading:{fontSize:30,fontWeight:'900'},sub:{opacity:.55,marginTop:-8},notice:{backgroundColor:'#172033',borderRadius:15,padding:13},noticeText:{color:'white',fontWeight:'800'},card:{backgroundColor:'white',borderRadius:20,padding:16,gap:10,elevation:1},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2,opacity:.5},row:{flexDirection:'row',gap:8},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},balance:{flex:1,backgroundColor:'#F4F6F9',padding:11,borderRadius:13},balanceValue:{fontSize:18,fontWeight:'900'},meta:{fontSize:12,opacity:.55},strong:{fontWeight:'800'},picker:{minHeight:48,borderWidth:1,borderColor:'#E1E5EC',borderRadius:13,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},action:{fontSize:12,color:'#246BFD',fontWeight:'800'},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:11,backgroundColor:'#EEF1F6'},selected:{backgroundColor:'#246BFD'},white:{color:'white',fontWeight:'800'},primary:{minHeight:48,borderRadius:14,backgroundColor:'#246BFD',alignItems:'center',justifyContent:'center'},primaryText:{color:'white',fontWeight:'900'},secondary:{minHeight:46,borderRadius:14,backgroundColor:'#EEF1F6',alignItems:'center',justifyContent:'center'},disabled:{opacity:.3},item:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,paddingVertical:7,borderBottomWidth:1,borderBottomColor:'#F0F2F5'},undo:{paddingHorizontal:11,paddingVertical:7,borderRadius:9,backgroundColor:'#FCECEC'},undoText:{fontWeight:'800',color:'#9B2C2C'}});
