import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { migrateDatabase } from './data/migrations';
import { getWallet, Wallet, xpProgress } from './data/economyRepository';
import { listCalendarBlocks } from './data/calendarRepository';
import { refreshTaskLocks } from './services/taskService';
import { TaskManager } from './screens/TaskManager';
import { FocusFlow } from './screens/FocusFlow';
import { CalendarBlock, FreeWindow, SessionPool } from './domain/types';
import { availableSessionPools, calculateFreeWindows, currentFreeWindow, difficultyCapacityMinutes, nextBlock, remainingMinutesInWindow } from './engine/timeline';

type Tab = 'today' | 'tasks';
function dayBounds(now=new Date()){const start=new Date(now);start.setHours(0,0,0,0);const end=new Date(now);end.setHours(23,59,59,999);return{start:start.toISOString(),end:end.toISOString()};}
function timeLabel(iso:string){return new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}

export default function App(){
  const[ready,setReady]=useState(false);const[tab,setTab]=useState<Tab>('today');const[focus,setFocus]=useState<{pool:SessionPool;free:number}|null>(null);
  useEffect(()=>{(async()=>{await migrateDatabase();await refreshTaskLocks();setReady(true)})().catch(e=>{console.error(e);setReady(true)})},[]);
  if(!ready)return <SafeAreaView style={styles.loading}><StatusBar style="dark"/><ActivityIndicator size="large"/><Text>Preparing your local workspace…</Text></SafeAreaView>;
  if(focus)return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><FocusFlow pool={focus.pool} freeMinutes={focus.free} onClose={()=>setFocus(null)}/></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><StatusBar style="dark"/>{tab==='today'?<TodayTimeline onStart={(pool,free)=>setFocus({pool,free})}/>:<TaskManager/>}<View style={styles.nav}><Pressable onPress={()=>setTab('today')} style={styles.navItem}><Text style={tab==='today'?styles.navActive:styles.navText}>Today</Text></Pressable><Pressable onPress={()=>setTab('tasks')} style={styles.navItem}><Text style={tab==='tasks'?styles.navActive:styles.navText}>Tasks</Text></Pressable></View></SafeAreaView>;
}

function TodayTimeline({onStart}:{onStart:(pool:SessionPool,free:number)=>void}){
  const[wallet,setWallet]=useState<Wallet>({coin:0,xp:0,level:1});const[blocks,setBlocks]=useState<CalendarBlock[]>([]);const[now,setNow]=useState(new Date());
  const load=useCallback(async()=>{const bounds=dayBounds();const[w,b]=await Promise.all([getWallet(),listCalendarBlocks(bounds.start,bounds.end)]);setWallet(w);setBlocks(b)},[]);
  useEffect(()=>{load().catch(console.error);const tick=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(tick)},[load]);
  const bounds=dayBounds(now);const windows=useMemo(()=>calculateFreeWindows(bounds.start,bounds.end,blocks),[bounds.start,bounds.end,blocks]);const current=currentFreeWindow(windows,now);const free=current?remainingMinutesInWindow(current,now):0;const pools=current?availableSessionPools(free):[];const next=nextBlock(blocks,now);const xp=xpProgress(wallet.xp);const difficultyCap=difficultyCapacityMinutes(windows);
  return <ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>TODAY</Text><Text style={styles.title}>Your timeline</Text></View><Text style={styles.level}>Lv. {wallet.level}</Text></View><View style={styles.xpCard}><View style={styles.xpHeader}><Text style={styles.xpTitle}>Level {wallet.level}</Text><Text style={styles.xpMeta}>{xp.earnedInLevel} / {xp.neededInLevel} XP</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${Math.max(2,xp.progress*100)}%`}]} /></View><Text style={styles.xpRemaining}>{xp.remainingToNextLevel} XP to Lv. {wallet.level+1}</Text></View><View style={styles.nextCard}><Text style={styles.nextLabel}>CURRENT WINDOW</Text><Text style={styles.nextTitle}>{current?`${free} min free`:'Protected / scheduled time'}</Text><Text style={styles.nextMeta}>{next?`Next · ${next.title} at ${timeLabel(next.startAt)}`:'No later calendar block today'}</Text>{current&&pools.length>0?<View style={styles.poolRow}>{pools.map(pool=><Pool key={String(pool)} label={pool==='deep'?'Deep':String(pool)} onPress={()=>onStart(pool,free)}/>)}</View>:null}</View><Timeline blocks={blocks} windows={windows}/><View style={styles.stats}><Text>🔥 Difficulty capacity · {Math.floor(difficultyCap/60)}h {difficultyCap%60}m today</Text><Text>🪙 {wallet.coin}   ·   Total XP {wallet.xp}</Text></View></ScrollView>;
}

function Timeline({blocks,windows}:{blocks:CalendarBlock[];windows:FreeWindow[]}){const items=[...blocks.map(b=>({id:b.id,start:b.startAt,label:b.title,free:false})),...windows.map(w=>({id:`free-${w.startAt}`,start:w.startAt,label:`FREE · ${w.durationMinutes} min`,free:true}))].sort((a,b)=>new Date(a.start).getTime()-new Date(b.start).getTime());return <View style={styles.timeline}>{items.length===0?<Text style={styles.empty}>No blocks yet · today is open.</Text>:items.map(item=><View key={item.id} style={styles.row}><Text style={styles.time}>{timeLabel(item.start)}</Text><View style={styles.line}/><Text style={[styles.event,item.free&&styles.free]}>{item.label}</Text></View>)}</View>}
function Pool({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.pool}><Text style={styles.poolText}>{label}</Text></Pressable>}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:14,backgroundColor:'#F7F8FA'},container:{padding:20,paddingBottom:90,gap:18},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{fontSize:12,fontWeight:'700',letterSpacing:1.5,opacity:.55},title:{fontSize:30,fontWeight:'700',marginTop:4},level:{fontWeight:'800'},xpCard:{backgroundColor:'white',borderRadius:20,padding:16,elevation:1,gap:9},xpHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},xpTitle:{fontWeight:'900',fontSize:16},xpMeta:{fontSize:12,fontWeight:'700',opacity:.55},progressTrack:{height:10,borderRadius:999,backgroundColor:'#E6EAF1',overflow:'hidden'},progressFill:{height:'100%',borderRadius:999,backgroundColor:'#246BFD'},xpRemaining:{fontSize:12,opacity:.5},nextCard:{backgroundColor:'white',borderRadius:24,padding:20,elevation:2},nextLabel:{fontSize:11,fontWeight:'700',letterSpacing:1.2,opacity:.5},nextTitle:{fontSize:24,fontWeight:'700',marginTop:6},nextMeta:{marginTop:5,opacity:.6},poolRow:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:16},pool:{minWidth:62,paddingVertical:12,paddingHorizontal:14,borderRadius:14,backgroundColor:'#246BFD',alignItems:'center'},poolText:{color:'white',fontWeight:'900'},timeline:{backgroundColor:'white',borderRadius:24,paddingVertical:8,paddingHorizontal:14},row:{minHeight:58,flexDirection:'row',alignItems:'center'},time:{width:62,fontSize:13,opacity:.55},line:{width:3,height:42,borderRadius:2,backgroundColor:'#D8DDE6',marginRight:14},event:{flex:1,fontSize:15,fontWeight:'600'},free:{fontWeight:'800'},empty:{padding:18,opacity:.5},stats:{gap:8,paddingHorizontal:4},nav:{position:'absolute',left:18,right:18,bottom:12,minHeight:58,borderRadius:22,backgroundColor:'white',flexDirection:'row',elevation:6,padding:6},navItem:{flex:1,alignItems:'center',justifyContent:'center'},navText:{fontWeight:'700',opacity:.45},navActive:{fontWeight:'900',color:'#246BFD'}});
